name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Give gradlew permission to execute
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: List files in build directory
      run: ls -R app/build/outputs/apk/release

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Deploy to Firebase (example)
      uses: actions/upload-artifact@v4
      with:
        name: firebase-deployment
        path: ./firebase-deploy-folder
