name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Give gradlew permission to execute
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    # Загрузка APK как артефакт для последующего использования
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: app/build/outputs/apk/release/app-release.apk

    # Настройка Firebase CLI
    - name: Set up Firebase CLI
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > firebase-service-account.json
        firebase use --add

    # Публикация APK в Firebase
    - name: Upload APK to Firebase App Distribution
      run: |
        firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk --app YOUR_FIREBASE_APP_ID --groups "testers" --token "$FIREBASE_AUTH_TOKEN"
      env:
        FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
