name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Настройка JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Разрешаем gradlew на выполнение
    - name: Give gradlew permission to execute
      run: chmod +x gradlew

    # 4. Сборка приложения с помощью Gradle
    - name: Build with Gradle
      run: ./gradlew assembleRelease  # Это создаст .apk файл в папке build

    # 5. Загрузка собранного .apk файла как артефакт
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2  # Используем стабильную версию v2
      with:
        name: app-apk
        path: app/build/outputs/apk/release/app-release.apk  # Путь к файлу .apk
